// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemBody } from "./ProblemBody";

export interface GetProblemResponse { problem_id: number, body: ProblemBody, }