// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ProblemExecutorResult } from "./ProblemExecutorResult";
export interface GetSubmissionsJson { output: ProblemExecutorResult, submission_id: string, status: string, language: string, submitted_at: bigint, }
