// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemID } from "./ProblemID";

export interface GetSubmissionsForm { problem_id: ProblemID, from: number, to: number, }