// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemExecutorResult } from "./ProblemExecutorResult";
import type { ProblemID } from "./ProblemID";

export interface GetSubmissionsResponse { problem_id: ProblemID, result: ProblemExecutorResult, to: number, }