// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";
import type { TestCaseResult } from "./TestCaseResult";

export interface ProblemExecutorResult { overall_result: Status, test_cases_results: Array<TestCaseResult>, prepare_output: { stdout: any , stderr : any , status: any } | null, }