// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemBody } from "./ProblemBody";
import type { ValidationType } from "./ValidationType";

export interface ProblemForm { body: ProblemBody, checker: string | null, validation: ValidationType, memory_limit: number, time_limit: number, is_public: boolean, }