// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProblemBody { information: string, identifier: string | null, name: string, input: string, output: string, problem: string, note: string | null, }