// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Status = "Pending" | "Accepted" | "WrongAnswer" | "TimeLimitExceeded" | "RuntimeError" | "PartialPoints" | "CompilationError" | { "UnknownError": string };