// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";

export interface Submission { problem: string, user: string, contest_id: string | null, language: Language, code: string, id: number, }
