// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";

export interface SubmitForm { language: Language, code: string, problem_id: number, contest_id: number | null, }