// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

export interface TestCaseResult { status: Status, id: number, output: { stdout: any , stderr : any , status: any } | null, }