// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemID } from "./ProblemID";

export interface TestCaseInfo { stdin_path: string, stdout_path: string | null, problem_id: ProblemID, id: string, }